name: KerasTensorFlowCoreML
channels:
- !!python/unicode
  'defaults'
dependencies:
- python=2.7
- pip==9.0.1
- numpy==1.12.0
- jupyter==1.0
- matplotlib==2.0.0
- scikit-learn==0.18.1
- scipy==0.19.0
- pandas==0.19.2
- pillow==4.0.0
- seaborn==0.7.1
- h5py==2.7.0
- pip:
  - tensorflow==1.1.0
  - keras==2.0.6
  - coremltools==0.6.3
